### ISSUE TITLE
What project name should we use?

### ISSUE THREAD

**Issue by forki** [fsprojects/FSharpx.Collections#1]
Hi,

I extracted all the collectections (including FSharpx.Collections.Experimental) from fsharpx and put them into this project.
I think it hsould be as easy as possible to use them and a dependency on FSharpx (the whole project) is often a big no-no.

This project has already > 1700 unit tests and some API documentation (will add FSharp.Formatting build task).

But what name/namespace should it get?

Here are some ideas:
- fsharp/Fsharpx.Collections
- fsharp/Fsharp.Collections
- fsharp/Fsharp.Data.Collections
- forki/Fsharpx.Collections
- ??

// cc @dsyme @ovatsus @mausch @tpetricek @mausch @jackfoxy @panesofglass

**Comment by jackfoxy** [comment]
I think this naming issue has been settled.
