### ISSUE TITLE
Travis build failing

### ISSUE THREAD

**Issue by jackfoxy** [fsprojects/FSharpx.Collections#109]
### Description

I think it started failing on this commit, or a commit soon after this. 

https://github.com/fsprojects/FSharpx.Collections/commit/a58e3ba332b31685ee7ef760c5ff2706c433db94

**Comment by jackfoxy** [comment]
Made some updates, problem is now:

"no environment variables set"

See this build script to fix:
https://github.com/fsprojects/FSharp.Control.Reactive/blob/704ac861853e5c132226f01b986207839a58662b/build.fsx#L102

**Comment by jackfoxy** [comment]
More progress

# to properly set Travis permissions: https://stackoverflow.com/questions/33820638/travis-yml-gradlew-permission-denied
# git update-index --chmod=+x fake.sh
# git commit -m "permission access for travis"

Now Travis failing in Expecto experimental tests...not sure why.

**Comment by gdziadkiewicz** [comment]
I "fixed" the problem in #138 by changing the target framework of the tests to netcoreapp21 and reducing the output from the tests (Travis terminates builds with output exceeding some limit).

**Comment by jackfoxy** [comment]
Thanks, @gdziadkiewicz !
