### ISSUE TITLE
AppVeyor builds are not shown as PRs checks.

### ISSUE THREAD

**Issue by gdziadkiewicz** [fsprojects/FSharpx.Collections#139]
### Description

~~AppVeyor builds are not triggered for Pull Requests.~~ The builds take place, but the status is not reported on the PR or commits. This may be similar to https://help.appveyor.com/discussions/problems/17150-github-doesnt-report-build-status-on-prs

### Repro steps

Please provide the steps required to reproduce the problem

1. Create PR

### Expected behavior

Checks from both Travis and AppVeyor visible.

### Actual behavior

Check only from Travis visible.

### Known workarounds

~~Setup your own AppVeyor account, execute the merge on your fork, trigger AppVeyor build and check the results.~~ Check the build status on AppVeyor page manually.

### Related information 

* Operating system N/A
* Branch N/A
* .NET Runtime, CoreCLR or Mono Version N/A
* Performance information, links to performance testing scripts N/A

**Comment by gdziadkiewicz** [comment]
Can the someone with permissions to modify https://ci.appveyor.com/project/fsgit/fsharpx-collections settings try to help or advise? @fsgit @fsprojectsgit ?

**Comment by gdziadkiewicz** [comment]
Commit checks:
![image](https://user-images.githubusercontent.com/8547855/66785953-0aee0700-eedf-11e9-89ec-0da34111a081.png)

PR checks:
![image](https://user-images.githubusercontent.com/8547855/66786028-425cb380-eedf-11e9-8758-ad7b636e61bc.png)

**Comment by sergey-tihon** [comment]
please check https://github.com/fsprojects/FSharpx.Collections/pull/92

**Comment by gdziadkiewicz** [comment]
@sergey-tihon Thanks for help. It seems to work now! What was the solution?

**Comment by sergey-tihon** [comment]
I am not sure... I created new AppVeyor project and it probably reregistered webhooks in the repo.

I personally prefer Azure Pipelines these days (one service,  one config file - runs on win, linux and macOS in the same time)
