### ISSUE TITLE
Is  FSharp.Core >= 4.3.4 still desirable/necessary?

### ISSUE THREAD

**Issue by jackfoxy** [fsprojects/FSharpx.Collections#153]
I believe this dependency
```
nuget FSharp.Core >= 4.3.4 lowest_matching:true
```
is for the benefit of some net45 library users.
Does this control the F# version building the collections library? 
@forki

**Comment by forki** [comment]
Yes it was needed for support of older net versions. I personally would go netstandard today

**Comment by gdziadkiewicz** [comment]
@jackfoxy 
It does not affect the version of the language as in compiler features (this is controlled by langversion in fsproj or in fsc call as described in https://devblogs.microsoft.com/dotnet/announcing-f-4-7/). This controls the version of standard lib used.

@forki 
I believe that is is not connected with the targeted framework  - it is controlled by NuGet package and every library is expected to state what is the minimal version of FSharp.Core that it requires. 


I added it during restoring support for net45 to explicitly state what is the minimum required version of FSharp.Core standard library as in https://fsharp.github.io/2015/04/18/fsharp-core-notes.html#libraries-should-target-lower-versions-of-fsharpcore . FSharp.Core 4.3.4 is the version suggested as the to-go version for netstandard2.0 and it happens to have all the standard library calls that were used in this project at this time.

I personally don't mind you to upgrade it to the latest 4.7 version if you need some of the new API, but it may make the new version not reachable for some potential other users that for some reason can't upgrade to FSharp.Core 4.7.

**Comment by jackfoxy** [comment]
@gdziadkiewicz  @forki  It is good to maintain a net45 version as long as possible to support users requiring that, and make sure it actually works for them.
 
I know there have been F# language performance improvements since F# 4.3.4. I am still not clear as to whether netstandard2.0 users achieve the benefits of these improvements. Runtime optimization is one of the qualities people look for in a collections library.

**Comment by gdziadkiewicz** [comment]
This is not a problem thanks to the fact that the end-user can use any
version of fsharp.core that matches >= 4.3.4, for example, the newest 4.7.0
with all of it's improved implementations of methods called by
FSharp.Collections. The only thing that we are not able to do due to this
constraint is to use APIs introduced after 4.3.4.
