### ISSUE TITLE
build fails, need to update FSharp.Formatting

### ISSUE THREAD

**Issue by jackfoxy** [fsprojects/FSharpx.Collections#164]
### Description

Build now fails in GenerateHelp target

`GenerateHelp            00:00:00.0116476   (Could not find a part of the path '<root>\FSharpx.Collections\packages\formatting\FSharp.Formatting\styles'.)`

### Repro steps

`.\fake`

The project's build needs to use the latest FSharp.Formatting.

**Comment by ronnieholm** [comment]
I'm not that familiar with FSharp.Formatting. 

What is it about the latest FSharp.Formatting that would make GenerateHelp work? It seems `packages/formatting/FSharp.Formatting/styles` disappeared between commits `b9cf8f3` and `24d1ff5` where FSharp.Formatting was updated from version 3.1.0 to 7.2.9.

**Comment by jackfoxy** [comment]
Strange that running fake.cmd on my local machine executes the `GenerateHelp` target, but Appveyor does not.
The FSharp.Formatting version in paket.lock, 7.2.9, is still quite old. Commit `24d1ff5` most likely broke that target, but I relied on the successful Appveyor build and did not build that PR locally.

> What is it about the latest FSharp.Formatting that would make GenerateHelp work? 

Actullay bringing the version forward to the most current release, 9.0.1, probably involves some work in build.fsx, I believe a lot has changed.

**Comment by jackfoxy** [comment]
Pretty sure the problem dates from commit `24d1ff5d627f3751ac07a59b672b2b4ffcedca08`, which updated `FSharp.Formatting` and `FSharp.Formatting.CommandTool` to `v7.2.9` from `v3.1`.
 
 Rolling back those 2 references via `paket update` caused a problem with the `paket.lock` file.
 
 So I think the best way forward is fixing the build targets that use `FSharp.Formatting` to work with `v7.2.9`
 
 This is not something I have the time to do anytime soon.

**Comment by sergey-tihon** [comment]
done in #177
