### ISSUE TITLE
Include source files in the Nuget package

### ISSUE THREAD

**Issue by bergmannjg** [fsprojects/FSharpx.Collections#185]
### Description

Please include the source files in the Nuget package to make the library compatible with the dotnet Fable tool.

A corresponding rule can be added to the files block in the paket.template file.

**Comment by njlr** [comment]
I think this library is already (somewhat) Fable compatible? Which version are you using?

See: https://github.com/fsprojects/FSharpx.Collections/blob/master/src/FSharpx.Collections/FSharpx.Collections.fsproj#L15

**Comment by bergmannjg** [comment]
I am using the nuget package version 3.0.1, which contains no fable folder.

The content itemgroup in FSharpx.Collections.fsproj is used by dotnet pack, but the nuget package is built with paket.

See: https://github.com/fsprojects/FSharpx.Collections/blob/master/build.fsx#L126

**Comment by njlr** [comment]
Ah I see!

This should fix it: https://github.com/fsprojects/FSharpx.Collections/pull/187

**Comment by bergmannjg** [comment]
Thanks

**Comment by njlr** [comment]
Will take a while for the review, merge, release cycle to complete (I don't have permissions)
