### ISSUE TITLE
Welcome gdziadkiewicz as co-maintainer!

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharpx.Collections#196]
Welcome to @gdziadkiewicz who is now a co-maintainer in this repo!

If you'd like to assist Grzegorz we're also looking for a second co-maintainer.

Best
@dsyme and @sergey-tihon

**Comment by dsyme** [comment]
@gdziadkiewicz We will need to make sure you can publish the nuget packages.  Generally this is done these days via a nuget token added as a GH secret that allow auto-publication from tagged releases.    These tokens last for one year.

**Comment by dsyme** [comment]
@gdziadkiewicz I've added a Actions secret to this repo for publishing the packages, under name NUGETKEY.  This can be used in auto-publishing from GH actions like this: 

https://github.com/fsprojects/FSharp.Data/blob/main/.github/workflows/push-master.yml#L35

(change `NUGET_ORG_TOKEN_2020` to `NGUETKEY`)

**Comment by gdziadkiewicz** [comment]
Thanks, I will check if it works as expected.

**Comment by gdziadkiewicz** [comment]
It works! https://github.com/fsprojects/FSharpx.Collections/actions/runs/3456767583/jobs/5769741558#step:9:3708 failed on doing a git commit (fix pending), but before that, it managed to release https://www.nuget.org/packages/FSharpx.Collections/3.1.0

**Comment by jackfoxy** [comment]
It was a good run for me as maintainer, and I'm happy to see the project is in good hands with @gdziadkiewicz 

Maintainer(s) in README.md should be updated.
