### ISSUE TITLE
1.9.4 from NuGet Gallery is corrupt now

### ISSUE THREAD

**Issue by ctaggart** [fsprojects/FSharpx.Collections#21]
The NuGet Gallery is now serving a corrupt `FSharpx.Collections.1.9.4.nupkg`. This started happening sometime between Friday and today, Monday. Our builds failed until I put an working copy in our AppVeyor NuGet feed.

```powershell
get-filehash $env:localappdata\nuget\cache\FSharpx.Collections.1.9.4.nupkg -algorithm md5
```

md5 of working: `B76B5AA6534862913BFC0F0B6775E3D8`
md5 of corrupt: `8AB7F69C9AB17E919CA96A07FB8D4B48`

This can see that the file is corrupt  by trying to open it up with NuGet Package Explorer:
![image](https://cloud.githubusercontent.com/assets/80104/5715402/2d461d98-9a8d-11e4-84ab-21910a9dfba6.png)

`paket restore` fails correctly with:
![image](https://cloud.githubusercontent.com/assets/80104/5715324/17504898-9a8c-11e4-947f-dca3d9d29251.png)

`nuget restore` appears to not do the check and does not fail.

**Comment by ctaggart** [comment]
Steps to reproduce:

```powershell
nuget install FSharpx.Collections -nocache
get-filehash .\FSharpx.Collections.1.9.4\FSharpx.Collections.1.9.4.nupkg -algorithm md5
```

![image](https://cloud.githubusercontent.com/assets/80104/5715476/3523ea58-9a8e-11e4-8c38-85313c9d1006.png)

**Comment by ctaggart** [comment]
Just opened https://nuget.codeplex.com/workitem/4415.

**Comment by forki** [comment]
Wtf? Do you want me to bump the version and deploy a zero diff version or
do think we should wait for @JeffHandley if he can comment on this?

**Comment by jeffhandley** [comment]
If a package gets edited on nuget.org, the package is rewritten and the hash changes.  The feed will then have the revised hash as well.

The Edit Package feature allows for descriptive metadata to be changed at any time.  But the feature didn't allow any behavior to change from the package.

Was this package edited perchance?

**Comment by forki** [comment]
I think @dsyme and me are the only persons with the rights to change this. I did nothing and I'm pretty sure Don has also no interest in changing meta.

We would just push a new version.

**Comment by sergey-tihon** [comment]
I changed latest version of the package. Link to logo was broken and I fixed it.
@forki Does it mean that we could not use online metadata editing and paket restore?
I am not sure that this is expected behavior in general ...

**Comment by forki** [comment]
ha!

no idea. If the feature breaks packages we should avoid it.

**Comment by forki** [comment]
I will push a new version.

**Comment by jeffhandley** [comment]
Paket should accommodate package edits.  The Last Edited Date is on the feed if that helps.

**Comment by forki** [comment]
please try 1.9.5

**Comment by sergey-tihon** [comment]
@jeffhandley sure, but this does not explain how `1.9.4` package became broken

**Comment by sergey-tihon** [comment]
@forki `1.9.5` is ok but without logo =(

**Comment by forki** [comment]
So what's wrong? Could you send pull request?

**Comment by ctaggart** [comment]
Mutable NuGet Packages =(

**Comment by forki** [comment]
It's completely strange. @jeffhandley  How can changing the meta data change the hash inside the package? We don't compare with any published hash. It's unzipping that fails. Even nuget package Explorer fails on this.

**Comment by jeffhandley** [comment]
I'm not looking at the details, FYI, but when a package is edited on nuget.org, we rewrite the nuspec and repack the nupkg.  This changes the nupkg's hash.
