### ISSUE TITLE
Implement IReadOnlyList<T> on PersistentVector?

### ISSUE THREAD

**Issue by bordoley** [fsprojects/FSharpx.Collections#25]
It would be useful (mostly for C# interop) if PersistentVector implemented IReadOnlyList.

**Comment by mausch** [comment]
There was a related discussion a couple of years ago: https://github.com/fsprojects/fsharpx/issues/35  , though that proposed change was broader.

A simpler solution would be setting up multi-targeting builds, and implement IReadOnlyList only for .NET 4.5 with an `#if`.

**Comment by bordoley** [comment]
I'd be in favor of that. Multi-target builds (PCL259, ios, android) would be incredibly useful too.

**Comment by mausch** [comment]
Sure, go ahead with that, sounds good to me. 
There is some of that already in https://github.com/fsprojects/FSharpx.Collections/blob/master/build.fsx  (see "BuildProfile47")
