### ISSUE TITLE
GetHashCode & thread safety

### ISSUE THREAD

**Issue by eacasanovaspedre** [fsprojects/FSharpx.Collections#35]
I have noticed that some of the collections implemented here rely on a mutable Option field to store the hashCode and that field is changed inside GetHashCode, making the collection "thread unsafe", even in collections that I would assume thread safe. Should not the code inside GetHashCode be surrounded by a lock? Is my thinking wrong in any way, or am I assuming what I should not?

**Comment by mausch** [comment]
Hi, which collections do you mean concretely?

**Comment by eacasanovaspedre** [comment]
Ahh, forget it. It took me a couple of hours after I posted this to figure it out. My mistake, I guess there is still a shared non-read-only memory space, concretely the mutable field hashCode, but since any thread entering there would assign it the same value (it depends on the same values) there is no problem, the worst that could happen is that the hash be computed more than once I suppose.
Heap and DList are two examples that have that "issue".
Nevertheless it can be improved to guarantee it's computed only once, but that is a tiny issue. So I'll close this.
