### ISSUE TITLE
MissingMethodException when using RandomAccessList.tryUpdate from F# 4.0 assembly

### ISSUE THREAD

**Issue by xavierzwirtz** [fsprojects/FSharpx.Collections#42]
I am referencing F# 4 from an assembly and FSharpx.Collections. When I attempt to use `RandomAccessList.tryUpdate` I get

```
System.MissingMethodException : Method not found: 'Microsoft.FSharp.Core.FSharpOption`1<FSharpx.Collections.RandomAccessList`1<!0>> FSharpx.Collections.RandomAccessList`1.TryUpdate(Int32, !0)'.
```

If I switch my assembly to reference F# 3.1 the exception does not occur.

**Comment by mausch** [comment]
Yes, this is as expected. As explained in https://fsharp.github.io/2015/04/18/fsharp-core-notes.html#fsharp-core-is-binary-compatible , FSharp.Core is binary compatible and "libraries should generally target the earliest, most portable version of FSharp.Core" and "applications should generally use the highest language version". You need a binding redirect in your project, also explained in that same document.

That said, the [Nuget package seems to be currently broken in its declared dependency](https://github.com/fsprojects/FSharpx.Collections/issues/43). Until that's fixed, as a workaround you should manually install the desired version of FSharp.Core for your application and check that the binding redirects are correct.

**Comment by jackfoxy** [comment]
no longer maintaining releases prior to 2.0
