### ISSUE TITLE
PriorityQueue API: IComparable vs comparison function

### ISSUE THREAD

**Issue by natec425** [fsprojects/FSharpx.Collections#48]
I'm just curious about the API decision to make the `PriorityQueue` require an `IComparable` (along with the `isDescending` parameter for `PriorityQueue.empty`) instead of using a comparison function parameter for `PriorityQueue.empty`.

To me, It seems like passing in a comparison function would be the more idiomatic thing, but I'm pretty new to FP/F# and would love to hear how I'm wrong =).

**Comment by thelazydogsback** [comment]
I was just going to post the same thing -- I wanted to use the PQ/Heap, but having the object decide how to compare itself against something else is not only non-idiomatic FP, but just seems like a bad idea borrowed from OOP that is not scalable in general - the object itself has no idea what "view" of itself is going to be necessary in various parts of the code for something like comparison.

**Comment by jackfoxy** [comment]
A 2.0 release is upcomming. Now is the time for breaking API changes. I'm also not entirely happy with the Heap API. @natec425  @thelazydogsback

**Comment by jackfoxy** [comment]
Happy to accept a PR into Collections.Experimental, or a non-breaking PR into Collections (2.0 will be released soon)
