### ISSUE TITLE
NuGet package: Could not load file or assembly 'FSharp.Core...

### ISSUE THREAD

**Issue by symbiotic** [fsprojects/FSharpx.Collections#60]
i just created an f# project for a console application and used NuGet to install FSharpx.Collections 1.14.0. i made a simple function to see how LazyList works. it compiles fine but when it runs, i get the following exception:

System.IO.FileLoadException was unhandled
Message: An unhandled exception of type 'System.IO.FileLoadException' occurred in myproject.exe
Additional information: Could not load file or assembly 'FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

on NuGet it says "Dependencies: FSharp.Core (≥ 3.0.0)". but in my Project > Properties > Application, it says "Target F# runtime: F# 3.1 (FSharp.Core, 4.3.1.0)" (the default). i'm using vs2013upd4

can you fix this?

**Comment by varon** [comment]
This happens in quite a few projects. You'll probably need to include binding redirects. 
Check this link for further info: https://fsharp.github.io/2015/04/18/fsharp-core-notes.html#use-binding-redirects-for-applications

**Comment by jackfoxy** [comment]
No longer maintaining pre-2.0beta releases
reopen if this is still an issue with 2.0
