### ISSUE TITLE
Nop thread comparison in PersistentHashMap

### ISSUE THREAD

**Issue by mrange** [fsprojects/FSharpx.Collections#66]
I am reviewing the code of `PersistentHashMap`, I am wonder if the following code is correct

``` fsharp
member this.ensureEditable(thread1, count1, array1) =
  if !thread = !thread then  // This test looks like its always true, shouldn't one of the operands be thread1
    this.array <- array1
    this.count <- count1
    this
  else HashCollisionNode(thread1, hashCollisionKey, count1, array1)
```

I am no expert on how to implement a `PersistentHashMap` so I might have misunderstood something.

**Comment by forki** [comment]
looks like a bug to me. PRs welcome

**Comment by mrange** [comment]
Is working on one but cracked my wrist so will take awhile

**Comment by jackfoxy** [comment]
@forki  relying on existing tests covering this
ready for beta4
