### ISSUE TITLE
Tagged collections, tagged map

### ISSUE THREAD

**Issue by iskrich** [fsprojects/FSharpx.Collections#68]
I have old project, that uses FSharp.PowerPack and I want to move some parts to FSharpx.Collections. 
After namespace transformation, I ran into a problem: 
PowerPack contains other collections, in particular, Tagged.Map
https://github.com/fsprojects/powerpack-archive/blob/master/src/FSharp.PowerPack/TaggedCollections.fs

There's some types in my project, like:
`type NamesMap<'v> = Tagged.Map<NameTypes.SomeName, 'v, NameTypes.NameComparer>
`
Can you recommend, what's the most convenient way to transform this code into your collections? Is it possible to transform, without code modification?

Thank you.

**Comment by mausch** [comment]
I don't think there are any tagged collections in FSharpx yet, but they would be a worthy addition.

A workaround would be creating a simple type that wraps `SomeName` and implements comparison as defined in `NameComparer`. Say you call this type `SomeNameWithCustomComparer`. Then just use the standard Map type with a key type `SomeNameWithCustomComparer`.

**Comment by iskrich** [comment]
Thank you, 

Can I make PR, which will include just copy of Microsoft PowerPack TaggedCollections?

**Comment by mausch** [comment]
I think it should be fine, considering that the LazyList here was also originally copied verbatim from PowerPack. It should keep the original copyright, of course.

**Comment by jackfoxy** [comment]
Merged into master, but namespace is ````Microsoft.FSharp.Collections.Tagged````

Since this namespace is being maintained in FSharpx, and not by Microsoft, I think it makes more sense to move this to change the namespace to ````FSharpx.Collections```` for 2.0.
