### ISSUE TITLE
complexity error in the pairing heap API

### ISSUE THREAD

**Issue by nestordemeure** [fsprojects/FSharpx.Collections#70]
Some (merge and insert) of the given complexities for the [pairing heap implementation](http://fsprojects.github.io/FSharpx.Collections/reference/fsharpx-collections-experimental-pairingheapmodule.html) seem to be wrong (it might be a copy-pasting error). 
They are not coherent with Chris Okasaki's [Functional Data Structures](http://www.westpoint.edu/eecs/SiteAssets/SitePages/Faculty%20Publication%20Documents/Okasaki/afp96.pdf) (p25), neither [wikipedia](https://en.wikipedia.org/wiki/Pairing_heap) (which has a source for the complexity of the delemin operation).

The correct values should be : 
- insert : O(1) worst case
- merge : O(1) worst case
- tryMerge : O(1) worst case

**Comment by jackfoxy** [comment]
@nestordemeure 
I Okasaki's Purely Functional Data structures: 

> Many imperative implementations support insert, merge ... in O(1)amortized time ... unfortunately, the bounds for pairing heaps have only been conjectured, not proved.

In the paper you cite he also hedges, a little. I couldn't find a publication data in that paper, btw.

The correct O(1) is amortized, not worst case. 

I would accept a PR with this change, if you are interested in doing it.

**Comment by nestordemeure** [comment]
It is O(1) amortized indeed. I just submitted a pull request with the corresponding modifications.

**Comment by jackfoxy** [comment]
https://github.com/fsprojects/FSharpx.Collections/pull/93
