### ISSUE TITLE
PersistentVector should implement IReadOnlyCollection

### ISSUE THREAD

**Issue by rmunn** [fsprojects/FSharpx.Collections#73]
### Description

The PersistentVector class (and any other list-like classes that know their own length as an O(1) operation, such as RandomAccessList) should probably implement [the `IReadOnlyCollection<'T>` interface](https://msdn.microsoft.com/en-us/library/hh881542(v=vs.110).aspx). It's a very simple interface, only requiring a `Count` property. The only tricky thing is that `IReadOnlyCollection<'T>` was added to .Net relatively recently, so it's only in .Net Framework starting with .Net Framework 4.5, it's only in Windows Phone starting with Windows Phone 8.1, and so on. So adding this interface would tend to break compatibility with some older .Net implementations, and thus it should be behind a compile-time flag that can turn it off if FSharpx.Collections is being built for an older profile. See, for example, how [the `FSCORE_PORTABLE_OLD` flag is defined](https://github.com/Microsoft/visualfsharp/pull/2587/commits/94551f1fe2dc841af5fc831aeda84d9423a08577) for some protable profiles (like profile 47), and how [that flag is used](https://github.com/Microsoft/visualfsharp/pull/2587/files/59e2c0418a6231de0d740cfb15cf080cb40d6c36#diff-d175f3dce65d9eceffb450fb8623ec05R463) to skip compiling non-portable bits on older systems.

### Pros

Once [the ISeq implementation](https://github.com/Microsoft/visualfsharp/pull/2587) gets merged in, it will be able to handle `PersistentVector`s far more efficiently in any situation where a count is required (such as the `Array.ofSeq` implementation that wants to know the length of the incoming data so it can pre-allocate an array to store the result). It would be a shame if a highly-efficient, persistent, immutable collection like `PersistentVector` ended up causing unnecessary O(N) operations that could have been skipped by simply adding a one-line interface implementation.

### Cons

The need to keep FSharpx.Collections portable to older .Net versions will necessarily increase the complexity of the project's build system; compiler directives are never nice things to see in one's code. The alternative to a compiler directive would be to explicitly abandon support .Net 4.0 and earlier, Windows Phone 8.0 and earlier, and so on.

**Comment by jackfoxy** [comment]
Accepting PRs for 2.0 on https://github.com/fsprojects/FSharpx.Collections/tree/netstandard branch @rmunn

**Comment by gdziadkiewicz** [comment]
Done in #146
