### ISSUE TITLE
.NET Standard support

### ISSUE THREAD

**Issue by teo-tsirpanis** [fsprojects/FSharpx.Collections#77]

**Comment by jackfoxy** [comment]
I'd be willing to look into doing a multi-target build.

**Comment by jackfoxy** [comment]
FSharp.Core 4.3.4 is not compatible with net40.
I think the only way to roll this project forward is to make a 2.0 release, multi-targeted to net45 and netstandard2.0. 

That being the case, I think I will tackle a couple additional items in a 2.0 release:
Convert tests to Expecto
Use FSharp.Formatting beta for better documentation generation

I'm happy to entertain other suggestions.

**Comment by teo-tsirpanis** [comment]
You can multi-target to .NET Standard 1.6, instead of 2.0. This is the minimum version FSharp.Core supports.

Sent from Mail for Windows 10

**Comment by jackfoxy** [comment]
does anyone in the F# community really use .NET Standard 1.6? I'll add it...

**Comment by jackfoxy** [comment]
...but if it came down to discovering any incompatibilities between 1.6 and 2.0, I would vote for restricting to 2.0

**Comment by teo-tsirpanis** [comment]
I have no problem either.

Sent from Mail for Windows 10

**Comment by jackfoxy** [comment]
@teo-tsirpanis  Adding netstandard1.6 generates lots of compile errors in the FSharpx.Collections project. I'm sticking to net45;netstandard2.0 for now. That combination of targets builds clean without any effort.. If anyone really wants to add  netstandard1.6 they will have to submit a PR later.

**Comment by panesofglass** [comment]
Didn’t @enricosada already submit a PR for this?

**Comment by panesofglass** [comment]
@jackfoxy, @enricosada closed it recently after six months of no response on the PR. See #80.

**Comment by enricosada** [comment]
I closed my PR because i want to send another, multitargeting netstandard2.0 and net45, because now all main editors support that (from VS 2017 15.6).

Unless real reason, for f# you shouldnt target `netstandard1.6`, just `netstandard2.0`.
The only good use of `netstandard1.6` is that can be used by .net core 1.0, that that's  unused now.

For F# doesnt matter `netstandard1.6` (and cannot target lower version because fsharp.core), 

You really want to use `netstandard2.0` for .net core, because allow to not have lots of packages dependecines from `NETStandard.Library` (for 2.0 are not needed), and TONS more of bcl api to use

You can see in https://github.com/dotnet/standard/blob/master/docs/versions.md , that .net 4.6.1 support the `netstandard2.0` already. the previous (`net46`) require .net standard1.3 (who cannot be done for f#).

So `netstandard2.0` and any `net4*` is ok for lib

**Comment by jackfoxy** [comment]
> I want to send another, multitargeting netstandard2.0 and net45

@enricosada  looking forward to seeing this.

**Comment by jackfoxy** [comment]
I would rather see this on a 2.0 (or other named) branch in this repo, but for now I have commited merged changes by @ChrSteinert  and myself to https://github.com/jackfoxy/FSharpx.Collections/tree/netstandard

This is my suggestion for further work on a 2.0 release.

## Immediate issues:

- [ ] Migrate tests to Expecto

Not absolutely necessary, but desirable to get on modern test framework and eliminate the following issues:

- [ ] Eliminate need for binding redirects and remove app.config files
- [ ] Fix "This construct is deprecated" warning from FSharpx.Collections.Tests and FSharpx.Collections.Experimental.Tests
- [ ] Could not load file or assembly 'nunit.framework' from following tests:

* Experimental.Tests.BinaryRoseTreeTest
* Experimental.Tests.EagerRoseTreeTest
* Experimental.Tests.IndexedRoseTreeTest
* Experimental.Tests.RingBufferTest
* Experimental.Tests.TimeSeriesTest

## Desireable enhancements for 2.0:

- [ ] nuget FSharp.Formatting prerelease 

* requires modifications to docs\tools\generate.fsx

- [ ] missing intellisense xml for several collections
- [ ] add doc pages for all FSharpx.Collections
- [ ] add Expecto BenchmarkDotNet test project and representative benchmarks

**Comment by jackfoxy** [comment]
@forki  and/or @mausch  please set up a branch for community PRs in moving the project forward to multitargeted and other enhancements, with the goal of a 2.0 release...
...or suggest another way to bring the project forward.

**Comment by forki** [comment]
I could add you as a maintener if you like

**Comment by jackfoxy** [comment]
@forki  OK

**Comment by forki** [comment]
good sent you team member request. you should be admin now. 
As first step: please add yourself to maintainers list in readme.
what's your nuget.org name?

**Comment by jackfoxy** [comment]
Nuget.org jackfoxy, thanks!

**Comment by jackfoxy** [comment]
@ChrSteinert  https://github.com/fsprojects/FSharpx.Collections/tree/netstandard set up as branch for developing 2.0.
See checklist a few messages up.

**Comment by forki** [comment]
Ok added you to nuget owners.

Jack Fox <notifications@github.com> schrieb am Fr., 27. Apr. 2018, 02:30:

**Comment by jackfoxy** [comment]
2.0 netstandard branch updated
all projects build
most Collections tests run, most of those pass
See https://github.com/fsprojects/FSharpx.Collections/issues/77#issuecomment-383395949 for project checklist
@ChrSteinert

**Comment by ChrSteinert** [comment]
I already had some success with my RegEx Fu to convert some NUnit tests to Expecto. So a) there is progress, b) I think it makes sense to move over to Expecto.

**Comment by monkieboy** [comment]
I think (if I am not missing something) that the `Expect.equal` can be changed to `Expect.sequenceEqual` to fix some of the Expecto tests. Would you like me to do that?

**Comment by jackfoxy** [comment]
@monkieboy  Certainly! And thanks for the Expecto tip.

**Comment by monkieboy** [comment]
I pushed a few tests that worked locally, but the build failed in Travis. I am not sure if the build was failing before or not, where can I check, I haven't used Travis before?

**Comment by monkieboy** [comment]
@jackfoxy I think I fixed the build, if I make a pull request it wants to take the previous commit too, should I submit that and you can clear out the other pull request or will you prefer to accept and then I submit the PR just for the build fix? I am not 100% sure I have fixed it until travis runs it, maybe there is a better way to verify than simply running the build.sh on my macbook?

**Comment by jackfoxy** [comment]
@monkieboy  if you have test fixes and travis fix in separate commits of single PR, that is OK.

**Comment by jackfoxy** [comment]
breaking change for 2.0:
https://github.com/fsprojects/FSharpx.Collections/issues/107

**Comment by jackfoxy** [comment]
2.0 beta released 
closing this issue
