### ISSUE TITLE
Travis CI build failing

### ISSUE THREAD

**Issue by rmunn** [fsprojects/FSharpx.Collections#81]
Travis CI build is currently failing due to a Paket issue of some kind: something about Travis CI's setup apparently makes it fail when Paket is run in "magic" mode. See https://github.com/fsprojects/Paket/issues/2588 for more details, and https://travis-ci.org/fsprojects/FSharpx.Collections/builds/247094934 for the most current failing build on the `master` branch.

**Comment by rmunn** [comment]
Looks like https://github.com/fsprojects/FSharpx.Collections/pull/78 would fix this issue.

**Comment by forki** [comment]
going back from magic mode? I think just updating the bootstrapper may help

**Comment by jackfoxy** [comment]
The last merge to master built successfully on travis
